name: frezra_messenger_mobile
description: "FrEzra Messenger Mobile App"
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: latest
  firebase_auth: latest
  cloud_firestore: latest
  firebase_storage: latest
  provider: latest
  http: latest
  socket_io_client: latest
  shared_preferences: latest

dev_dependencies:
  flutter_lints: latest
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
